import { jsPDF } from 'jspdf';

/**
 * Robust helper to fetch an image from a URL and convert it to a Base64 string.
 * Uses CORS-enabled corporate CDN pathways with fallback capability.
 */
function getLogoBase64() {
  const fallbackUrls = [
    'https://images.shiksha.com/mediadata/images/1572944360phpGgOfmD.png',
    'https://images.yourstory.com/cs/images/companies/iamneo-1647413340573.png',
    'https://logo.clearbit.com/iamneo.ai',
    'https://logo.clearbit.com/iamneo.com'
  ];

  return new Promise((resolve) => {
    let index = 0;
    const img = new Image();
    img.crossOrigin = 'anonymous';

    const tryNext = () => {
      if (index >= fallbackUrls.length) {
        // Resolve with null if all network paths fail
        resolve(null);
        return;
      }
      img.src = fallbackUrls[index++];
    };

    img.onload = () => {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = img.naturalWidth || img.width;
        canvas.height = img.naturalHeight || img.height;
        const ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0);
        resolve(canvas.toDataURL('image/png'));
      } catch (err) {
        tryNext();
      }
    };

    img.onerror = () => {
      tryNext();
    };

    tryNext();
  });
}

/**
 * Robust, highly-aligned PDF Exporter with iamneo badging and corporate metadata.
 * Generates pristine PDFs with auto-wrapping, beautiful layouts, color-coded sections, 
 * shaded example/test-case blocks, code blocks, and strict pagination alignment.
 */
export async function downloadQuestionsAsPDF(questions, options = {}) {
  const {
    track = 'N/A',
    course = 'N/A',
    client = 'N/A',
    stack = 'N/A',
    userName = 'Sai Deepak D Y',
    userEmpId = 'neo10506',
    time = new Date().toLocaleString()
  } = options;

  // Retrieve corporate brand image badge first in browser context
  const logoDataUri = await getLogoBase64();

  const doc = new jsPDF('p', 'mm', 'a4');
  let currentPageNum = 1;
  const marginX = 15;
  const contentWidth = 180; // 210 - 30 margin

  // Render iamneo Corporate Header
  const drawPageHeader = (pdf, pageNum) => {
    // Top light teal background accent header bar
    pdf.setFillColor(244, 251, 252); // Very soft brand teal
    pdf.rect(10, 8, 190, 30, 'F');
    pdf.setDrawColor(204, 235, 240);
    pdf.setLineWidth(0.4);
    pdf.rect(10, 8, 190, 30, 'D');

    if (logoDataUri) {
      // Draw actual exact badge image with zero quality loss
      try {
        pdf.addImage(logoDataUri, 'PNG', 14, 11, 46, 24);
      } catch (e) {
        // Fallback drawing if addImage fails
        drawTextFallbackLogo(pdf);
      }
    } else {
      drawTextFallbackLogo(pdf);
    }

    // Vertical divider line
    pdf.setDrawColor(218, 228, 230);
    pdf.setLineWidth(0.4);
    pdf.line(65, 12, 65, 34);

    // Right Pane Info Grid
    pdf.setFontSize(7.5);
    pdf.setTextColor(100, 116, 139); // slate-500
    
    // Row 1
    pdf.setFont('Helvetica', 'bold');
    pdf.text('GENERATED BY:', 70, 15);
    pdf.setFont('Helvetica', 'normal');
    pdf.text(`${userName} (${userEmpId})`, 95, 15);

    // Row 2
    pdf.setFont('Helvetica', 'bold');
    pdf.text('BUSINESS CLIENT:', 70, 20);
    pdf.setFont('Helvetica', 'normal');
    pdf.text(`${client}`, 95, 20);

    // Row 3
    pdf.setFont('Helvetica', 'bold');
    pdf.text('STACK / TRACK:', 70, 25);
    pdf.setFont('Helvetica', 'normal');
    pdf.text(`${stack} | ${track}`, 95, 25);

    // Row 4
    pdf.setFont('Helvetica', 'bold');
    pdf.text('COURSE & TIME:', 70, 30);
    pdf.setFont('Helvetica', 'normal');
    pdf.text(`${course}  |   ${time}`, 95, 30);
  };

  const drawTextFallbackLogo = (pdf) => {
    // Draw modern icon/mark on the left
    pdf.setFillColor(16, 185, 129); // iamneo brand emerald accent dot
    pdf.circle(16, 21, 1.8, 'F');
    
    // iamneo Logotype
    pdf.setTextColor(30, 41, 59); // slate-800
    pdf.setFont('Helvetica', 'normal');
    pdf.setFontSize(14);
    pdf.text('iam', 20, 23);

    pdf.setFont('Helvetica', 'bold');
    pdf.setFontSize(14.5);
    pdf.setTextColor(15, 23, 42); // slate-900
    pdf.text('neo', 29, 23);

    // NIIT Venture Sub-tag
    pdf.setFont('Helvetica', 'normal');
    pdf.setFontSize(6.5);
    pdf.setTextColor(71, 85, 105); // slate-600
    pdf.text('An NIIT venture', 20, 27);
  };

  const drawPageFooter = (pdf, pageNum) => {
    // Bottom boundary line
    pdf.setDrawColor(226, 232, 240); // border-slate-200
    pdf.setLineWidth(0.3);
    pdf.line(15, 282, 195, 282);

    // Metadata lines
    pdf.setFont('Helvetica', 'normal');
    pdf.setFontSize(7.5);
    pdf.setTextColor(148, 163, 184); // slate-400
    pdf.text('QuestAI • Enterprise Content Engineering Ecosystem', 15, 288);
    pdf.text(`Page ${pageNum}`, 185, 288, { align: 'right' });
  };

  // Pre-initialize first page
  drawPageHeader(doc, currentPageNum);
  drawPageFooter(doc, currentPageNum);

  // Vertical offset cursor starts below header (44mm spacer)
  let y = 46;

  // Safe wrapper for drawing lines with overflow safety audits built-in
  const addWrappedText = (pdf, text, x, fontName = 'Helvetica', fontStyle = 'normal', fontSize = 9, colorRGB = [51, 65, 85], spacing = 4.5, italic = false, maxWidth = contentWidth) => {
    if (!text) return y;
    pdf.setFont(fontName, fontStyle);
    pdf.setFontSize(fontSize);
    pdf.setTextColor(colorRGB[0], colorRGB[1], colorRGB[2]);
    
    const lines = pdf.splitTextToSize(String(text), maxWidth);
    for (let i = 0; i < lines.length; i++) {
      if (y > 270) {
        pdf.addPage();
        currentPageNum++;
        drawPageHeader(pdf, currentPageNum);
        drawPageFooter(pdf, currentPageNum);
        y = 46;
        pdf.setFont(fontName, fontStyle);
        pdf.setFontSize(fontSize);
        pdf.setTextColor(colorRGB[0], colorRGB[1], colorRGB[2]);
      }
      pdf.text(lines[i], x, y);
      y += spacing;
    }
    return y;
  };

  const checkPageOverflow = (pdf, neededHeight) => {
    if (y + neededHeight > 270) {
      pdf.addPage();
      currentPageNum++;
      drawPageHeader(pdf, currentPageNum);
      drawPageFooter(pdf, currentPageNum);
      y = 46;
      return true;
    }
    return false;
  };

  // Document Title introduction block
  y = addWrappedText(doc, `Course Bank: ${course}`, marginX, 'Helvetica', 'bold', 12, [30, 41, 59], 6);
  y = addWrappedText(doc, `Technology Stream: ${track}  |  Compiled Assessment Set`, marginX, 'Helvetica', 'normal', 9.5, [71, 85, 105], 4.5);
  
  // Custom styled spacer rule line
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(marginX, y + 2, marginX + contentWidth, y + 2);
  y += 6;

  // Map individual question list
  questions.forEach((q, qIdx) => {
    const isCoding = q._packType === 'coding';
    
    checkPageOverflow(doc, 15); // Pre-check a small buffer spacing
    
    // Draw Category Tag (MCQ / CODING) with dynamic style color
    const badgeColorRGB = isCoding ? [79, 70, 229] : [16, 185, 129]; // Indigo vs Green
    const badgeText = isCoding ? 'CODING PRACTICE' : 'MULTIPLE CHOICE QUESTION (MCQ)';

    // Thin elegant sidebar block for the question header
    doc.setFillColor(badgeColorRGB[0], badgeColorRGB[1], badgeColorRGB[2]);
    doc.rect(marginX, y, 4, 11, 'F');

    y = addWrappedText(doc, `Q${qIdx + 1}. ${badgeText}`, marginX + 6, 'Helvetica', 'bold', 8, badgeColorRGB, 4);
    
    let difficultyColor = [16, 185, 129];
    if (q.difficulty === 'Medium') difficultyColor = [245, 158, 11];
    if (q.difficulty === 'Hard') difficultyColor = [239, 68, 68];

    let headerTitle = q.title || q.question || 'Untitled Question Prompt';
    if (!isCoding && q.questions && q.questions[0]) {
      // In case we're holding a multi-nested MCQ object
      headerTitle = q.questions[0].question || headerTitle;
    }

    y = addWrappedText(doc, headerTitle, marginX + 6, 'Helvetica', 'bold', 10.5, [15, 23, 42], 5);
    
    // Additional metadata status row
    let metaTxt = `Difficulty: ${q.difficulty}`;
    if (q.leetcodeNumber) metaTxt += `  |  Leetcode Constraint: #${q.leetcodeNumber}`;
    if (q.companyTags && q.companyTags.length) metaTxt += `  |  Target Companies: ${q.companyTags.join(', ')}`;
    y = addWrappedText(doc, metaTxt, marginX + 6, 'Helvetica', 'bold', 8, [100, 116, 139], 4.5);
    y += 2; // Extra spacer cushion

    if (isCoding) {
      // 1. CODING QUESTION SCENARIO
      if (q.description) {
        y = addWrappedText(doc, 'PROBLEM DESCRIPTION:', marginX + 6, 'Helvetica', 'bold', 8.5, [71, 85, 105], 4);
        y = addWrappedText(doc, q.description, marginX + 6, 'Helvetica', 'normal', 9, [51, 65, 85], 4.5);
        y += 1.5;
      }

      // Check for constraints
      if (q.constraints && q.constraints.length) {
        checkPageOverflow(doc, 10);
        y = addWrappedText(doc, 'CONSTRAINTS & COMPLEXITY:', marginX + 6, 'Helvetica', 'bold', 8.5, [71, 85, 105], 4);
        const conStr = Array.isArray(q.constraints) ? q.constraints.join(' \u2022 ') : q.constraints;
        y = addWrappedText(doc, conStr, marginX + 8, 'Helvetica', 'normal', 8.5, [127, 29, 29], 4);
        y += 1.5;
      }

      // Input/Output Sample Specification card box - ALL 15 cases are printed correctly with neat spacing
      if (q.testCases && q.testCases.length) {
        checkPageOverflow(doc, 15);
        y = addWrappedText(doc, `VERIFICATION SUITE / GLOBAL TEST CASES (${q.testCases.length}):`, marginX + 6, 'Helvetica', 'bold', 8.5, [71, 85, 105], 4);
        
        q.testCases.forEach((tc, tcIdx) => {
          checkPageOverflow(doc, 18);
          
          // Shaded small container for the testcase details
          const boxYStart = y;
          doc.setFillColor(248, 250, 252); // soft slate background
          doc.rect(marginX + 6, boxYStart, contentWidth - 6, 13, 'F');
          doc.setDrawColor(226, 232, 240);
          doc.rect(marginX + 6, boxYStart, contentWidth - 6, 13, 'D');

          // Render inputs
          y += 1;
          addWrappedText(doc, `Case #${tcIdx + 1} Input: ${tc.input || tc.input_data || 'N/A'}`, marginX + 9, 'Courier', 'bold', 7.5, [47, 72, 88], 3.5, false, contentWidth - 12);
          y = addWrappedText(doc, `Expected Yield: ${tc.output || tc.output_data || tc.expected || 'N/A'}`, marginX + 9, 'Courier', 'bold', 7.5, [13, 148, 136], 3.5, false, contentWidth - 12);
          y += 3.5; // Padding spacing
        });
      }

      // Optimal implementation Starter code/Solution block formatted inside Dark Monospace container
      if (q.starterCode || q.optimalSolution || q.code) {
        checkPageOverflow(doc, 30);
        const codeText = q.starterCode || q.optimalSolution || q.code;
        y = addWrappedText(doc, 'OPTIMAL IMPLEMENTATION MATRIX:', marginX + 6, 'Helvetica', 'bold', 8.5, [71, 85, 105], 4);
        
        // Measure the target lines count for drawing high-fidelity dark text board
        const codeLines = doc.splitTextToSize(codeText, contentWidth - 12);
        const neededHeight = (codeLines.length * 3.5) + 6;
        
        checkPageOverflow(doc, neededHeight);

        const fillY = y;
        doc.setFillColor(15, 23, 42); // deep corporate dark blue-slate
        doc.rect(marginX + 6, fillY, contentWidth - 6, neededHeight, 'F');
        
        y += 3;
        // Output text inside the dark board using crisp Courier monospace font
        y = addWrappedText(doc, codeText, marginX + 9, 'Courier', 'normal', 7.5, [248, 250, 252], 3.3, false, contentWidth - 12);
        y += 4;
      }

    } else {
      // 2. MCQ QUESTION SCENARIO
      let qText = q.question;
      if (!qText && q.questions && q.questions[0]) {
        qText = q.questions[0].question;
      }
      if (qText && qText !== headerTitle) {
        y = addWrappedText(doc, qText, marginX + 6, 'Helvetica', 'normal', 9, [51, 65, 85], 4.5);
      }

      // Render Options Formats [A], [B], [C], [D]
      let opts = q.options || [];
      if ((!opts || opts.length === 0) && q.questions && q.questions[0]) {
        opts = q.questions[0].options || [];
      }

      if (opts && opts.length >= 4) {
        checkPageOverflow(doc, 22);
        y = addWrappedText(doc, 'SELECT FROM OPTIONS:', marginX + 6, 'Helvetica', 'bold', 8.5, [71, 85, 105], 4);
        
        opts.forEach((opt, oIdx) => {
          checkPageOverflow(doc, 8);
          const letter = String.fromCharCode(65 + oIdx);
          const isCorrect = oIdx === q.correctAnswer || (q.questions && oIdx === q.questions[0]?.correctAnswer);
          const blockColor = isCorrect ? [16, 185, 129] : [51, 65, 85];
          const textFormat = isCorrect ? 'bold' : 'normal';

          // Option checkbox rectangle guide
          doc.setDrawColor(203, 213, 225);
          doc.setFillColor(isCorrect ? 240 : 255, isCorrect ? 253 : 255, isCorrect ? 250 : 255);
          doc.rect(marginX + 6, y - 3, 4, 4, isCorrect ? 'FD' : 'D');
          if (isCorrect) {
            doc.setFillColor(16, 185, 129);
            doc.rect(marginX + 7, y - 2, 2, 2, 'F');
          }

          addWrappedText(doc, `[${letter}]  ${opt}`, marginX + 13, 'Helvetica', textFormat, 8.5, blockColor, 4, false, contentWidth - 14);
          y += 4.5;
        });
        y += 1.5;
      }

      // Explanation/Reasoning
      let expl = q.explanation;
      if (!expl && q.questions && q.questions[0]) {
        expl = q.questions[0].explanation;
      }

      if (expl) {
        checkPageOverflow(doc, 15);
        y = addWrappedText(doc, 'ANSWER COGNITIVE EXPLANATION:', marginX + 6, 'Helvetica', 'bold', 8.5, [71, 85, 105], 4);
        
        const correctChar = String.fromCharCode(65 + (q.correctAnswer !== undefined ? q.correctAnswer : q.questions?.[0]?.correctAnswer || 0));
        
        const fullExplText = `Correct Answer Option: [${correctChar}]\n${expl}`;
        y = addWrappedText(doc, fullExplText, marginX + 6, 'Helvetica', 'normal', 8.5, [6, 95, 70], 4, true); // Italic dark green emerald box text style
        y += 2;
      }
    }

    // Divider accent between cards
    checkPageOverflow(doc, 6);
    doc.setDrawColor(241, 245, 249);
    doc.line(marginX, y + 2, marginX + contentWidth, y + 2);
    y += 7;
  });

  // Final document binary layout save
  const sanitizedTopic = String(course || 'QuestAI_Report').replace(/[^a-z0-9]/gi, '_').toLowerCase();
  doc.save(`QuestAI_Report_Badged_${sanitizedTopic}.pdf`);
}
